idf_component_register(
    SRCS
        "main.c"
        "wifi_manager.c"
        "packet_rx.c"
        "frame_buffer.c"
        "web_server.c"
        "config_manager.c"
        "usb_network.c"
    INCLUDE_DIRS
        "."
    EMBED_FILES
        "../frontend/index.html"
        "../frontend/app.js"
        "../frontend/style.css"
    REQUIRES
        esp_wifi
        nvs_flash
        esp_http_server
        esp_netif
)
