#pragma once

#ifdef CONFIG_BOARD_ESP32S3ETH
// ESP32-S3-ETH
// Camera
#define CAM_PIN_PWDN    CONFIG_PIN_PWDN
#define CAM_PIN_RESET   CONFIG_PIN_RESET
#define CAM_PIN_XCLK    CONFIG_PIN_XCLK
#define CAM_PIN_SIOD    CONFIG_PIN_SIOD
#define CAM_PIN_SIOC    CONFIG_PIN_SIOC

#define CAM_PIN_D7      CONFIG_PIN_D7
#define CAM_PIN_D6      CONFIG_PIN_D6
#define CAM_PIN_D5      CONFIG_PIN_D5
#define CAM_PIN_D4      CONFIG_PIN_D4
#define CAM_PIN_D3      CONFIG_PIN_D3
#define CAM_PIN_D2      CONFIG_PIN_D2
#define CAM_PIN_D1      CONFIG_PIN_D1
#define CAM_PIN_D0      CONFIG_PIN_D0
#define CAM_PIN_VSYNC   CONFIG_PIN_VSYNC
#define CAM_PIN_HREF    CONFIG_PIN_HREF
#define CAM_PIN_PCLK    CONFIG_PIN_PCLK

// SD Card
#define CAM_SD_CS       CONFIG_PIN_CAM_SD_CS
#define CAM_SD_MOSI     CONFIG_PIN_CAM_SD_MOSI
#define CAM_SD_MISO     CONFIG_PIN_CAM_SD_MISO
#define CAM_SD_SCLK     CONFIG_PIN_CAM_SD_SCLK

// Ethernet
#define ETH_MISO_PIN    CONFIG_PIN_ETH_MISO
#define ETH_MOSI_PIN    CONFIG_PIN_ETH_MOSI
#define ETH_SCLK_PIN    CONFIG_PIN_ETH_SCLK
#define ETH_CS_PIN      CONFIG_PIN_ETH_CS
#define ETH_RST_PIN     CONFIG_PIN_ETH_RST
#define ETH_INT_PIN     CONFIG_PIN_ETH_INT

// RGB LED
#define RGB_LED_PIN     CONFIG_PIN_RGB_LED

#elif CONFIG_BOARD_ESP32S3SENSE
// ESP32-S3-SENSE
// Camera
#define CAM_PIN_PWDN    CONFIG_PIN_PWDN
#define CAM_PIN_RESET   CONFIG_PIN_RESET
#define CAM_PIN_XCLK    CONFIG_PIN_XCLK
#define CAM_PIN_SIOD    CONFIG_PIN_SIOD
#define CAM_PIN_SIOC    CONFIG_PIN_SIOC

#define CAM_PIN_D7      CONFIG_PIN_D7
#define CAM_PIN_D6      CONFIG_PIN_D6
#define CAM_PIN_D5      CONFIG_PIN_D5
#define CAM_PIN_D4      CONFIG_PIN_D4
#define CAM_PIN_D3      CONFIG_PIN_D3
#define CAM_PIN_D2      CONFIG_PIN_D2
#define CAM_PIN_D1      CONFIG_PIN_D1
#define CAM_PIN_D0      CONFIG_PIN_D0
#define CAM_PIN_VSYNC   CONFIG_PIN_VSYNC
#define CAM_PIN_HREF    CONFIG_PIN_HREF
#define CAM_PIN_PCLK    CONFIG_PIN_PCLK

// RGB LED
#define RGB_LED_PIN     CONFIG_PIN_RGB_LED

#elif CONFIG_BOARD_ESP32CAM
// ESP32-CAM
// Camera
#define CAM_PIN_PWDN    CONFIG_PIN_PWDN
#define CAM_PIN_RESET   CONFIG_PIN_RESET
#define CAM_PIN_XCLK    CONFIG_PIN_XCLK
#define CAM_PIN_SIOD    CONFIG_PIN_SIOD
#define CAM_PIN_SIOC    CONFIG_PIN_SIOC

#define CAM_PIN_D7      CONFIG_PIN_D7
#define CAM_PIN_D6      CONFIG_PIN_D6
#define CAM_PIN_D5      CONFIG_PIN_D5
#define CAM_PIN_D4      CONFIG_PIN_D4
#define CAM_PIN_D3      CONFIG_PIN_D3
#define CAM_PIN_D2      CONFIG_PIN_D2
#define CAM_PIN_D1      CONFIG_PIN_D1
#define CAM_PIN_D0      CONFIG_PIN_D0
#define CAM_PIN_VSYNC   CONFIG_PIN_VSYNC
#define CAM_PIN_HREF    CONFIG_PIN_HREF
#define CAM_PIN_PCLK    CONFIG_PIN_PCLK

// RGB LED
#define RGB_LED_PIN     CONFIG_PIN_RGB_LED
#define CAM_PIN_GND     3V3 // ESP32CAM uses 3V3 for GND

#else
#error "Board not selected in Kconfig"
#endif
